# Generated by Django 2.2.4 on 2020-09-12 15:57

from django.db import migrations

import phonenumbers

REGION_CODE = 'RU'


def set_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone = phonenumbers.parse(flat.owners_phonenumber, REGION_CODE)
        if phonenumbers.is_valid_number(pure_phone):
            flat.owner_pure_phone = pure_phone
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_auto_20200910_1711'),
    ]

    operations = [
        migrations.RunPython(set_pure_phone)
    ]
