# Generated by Django 2.2.4 on 2020-09-22 12:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20200912_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owners_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('flats', models.ManyToManyField(blank=True, related_name='owned_by', to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
