# Generated by Django 2.2.4 on 2020-09-22 12:47

from django.db import migrations


def populate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber, defaults={
            'owner_pure_phone': flat.owner_pure_phone
        })


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_auto_20200922_1545'),
    ]

    operations = [
        migrations.RunPython(populate_owners)
    ]
