# Generated by Django 2.2.4 on 2020-09-22 15:38

from django.db import migrations


def pair_owners_with_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    # sync owners from flats table with owners table and make connection
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber, defaults={
            'owner_pure_phone': flat.owner_pure_phone
        })
        owner.flats.set([flat])


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20200922_1713'),
    ]

    operations = [migrations.RunPython(pair_owners_with_flats)
                  ]
